services:

    auth.provider.cogauth:
        class: mrfg\cogauth\auth\provider\cogauth
        arguments:
           - '@captcha.factory'
           - '@config'
           - '@dbal.conn'
           - '@passwords.manager'
           - '@request'
           - '@user'
           - '%core.root_path%'
           - '%core.php_ext%'
           - '@mrfg.cogauth.cognito'
           - '@mrfg.cogauth.cognito_controller'
        tags:
            - { name: auth.provider }
