services:
    auth.provider.cogauth:
        class: mrfg\cogauth\auth\provider\cogauth
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@passwords.manager'
            - '@user'
            - '@mrfg.cogauth.user'
            - '@language'
            - '@service_container'
            - '@mrfg.cogauth.cognito'
            - '@log'

        tags:
            - { name: auth.provider }
