
services:
    mrfg.cogauth.listener:
        class: mrfg\cogauth\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
imports:
- { resource: auth.yml }


