
services:
    mrfg.cogauth.listener:
        class: mrfg\cogauth\event\main_listener
        arguments:
            - '@user'
            - '@mrfg.cogauth.cognito'
            - '@mrfg.cogauth.auth_result'
            - '@mrfg.cogauth.cognito_controller'
            - '@dispatcher'
            - '@request'
            - '@config'
            - '@template'

        tags:
            - { name: event.listener }

    mrfg.cogauth.controller:
        class: mrfg\cogauth\controller\main
        arguments:
            - '@config'
            - '@request'
            - '@mrfg.cogauth.auth_result'
            - '@language'
            - '@controller.helper'
            - '@user'
            - '@auth'

    mrfg.cogauth.cognito_controller:
        class: mrfg\cogauth\cognito\controller
        arguments:
            - '@user'
            - '@mrfg.cogauth.auth_result'
            - '@mrfg.cogauth.cognito'

    mrfg.cogauth.auth_result:
        class: mrfg\cogauth\cognito\auth_result
        arguments:
            - '@mrfg.cogauth.web_token_phpbb'
            - '@dbal.conn'
            - '@log'
            - '%mrfg.cogauth.tables.cogauth_authentication%'

    mrfg.cogauth.cognito:
        class: mrfg\cogauth\cognito\cognito
        arguments:
            - '@config'
            - '@user'
            - '@language'
            - '@request'
            - '@log'
            - '@mrfg.cogauth.web_token_phpbb'
            - '@mrfg.cogauth.user'
            - '@mrfg.cogauth.auth_result'
            - '@aws.sdk'


    mrfg.cogauth.user:
        class: mrfg\cogauth\cognito\user
        arguments:
            - '@dbal.conn'

    mrfg.cogauth.web_token_phpbb:
        class: mrfg\cogauth\cognito\web_token_phpbb
        arguments:
            - '@config'
            - '@cache.driver'
            - '%mrfg.cogauth.jwsk_url_template%'

    mrfg.cogauth.access_token_cleanup:
        class: mrfg\cogauth\cron\task\access_token_cleanup
        arguments:
            - '@config'
            - '@mrfg.cogauth.auth_result'
        calls:
            - [set_name, [cogauth.cron.access_token_cleanup]]
        tags:
            - { name: cron.task }

    aws.sdk:
        class: Aws\Sdk


imports:
- { resource: auth.yml }
- { resource: tables.yml }
- { resource: parameters.yml }
