
services:
    mrfg.cogauth.listener:
        class: mrfg\cogauth\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@mrfg.cogauth.cognito'
            - '%mrfg.cogauth.tables.cogauth_session%'
        tags:
            - { name: event.listener }


    mrfg.cogauth.cognito:
        class: mrfg\cogauth\cognito\cognito
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@user'
            - '%mrfg.cogauth.tables.cogauth_session%'

imports:
- { resource: auth.yml }
- { resource: tables.yml }


