services:
    mrfg.cogauth.controller:
        class: mrfg\cogauth\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'

    mrfg.cogauth.listener:
        class: mrfg\cogauth\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
